### ISSUE TITLE
Publishing a new version for the package

### ISSUE THREAD

**Issue by willmendesneto** [americanexpress/react-albus#109]
Hey folks 👋

I can see there are a lot of issues that were solved, but there's no new version shipping these new changes, fixes, etc.

Could you publish a new version, please? It will be great for the package consumers to get some issues removed and some goods added on the package ready to everyone

**Comment by willmendesneto** [comment]
Could you take a look at that, please @nellyk @asutedja @JamesSingleton  @smackfu? Is there anything I can do to help with that?

**Comment by Kienan6** [comment]
I recently had to fork the current repo/build it and pull it into my project. +1 to this. The current code base had some features that I needed that were not present in the 2017 build.

**Comment by n370** [comment]
+1

**Comment by donnfelker** [comment]
Agreed. I'm pulling from a branch and I'll probably fork it so future changes in the 3.x branch don't bork my clients build. A new release would be paramount right now.

**Comment by nellyk** [comment]
hey everyone, apologies for the delays, we shall be working to get a release out for this. It has been a while since it was updated and we have had some changes in contributors

**Comment by kristho91** [comment]
This would be most appreciated. Are there any ETA on this? :)

**Comment by willmendesneto** [comment]
I was waiting for the new version, but due to the lack of updates of this project I just decided to move on and create React Sweet State, a lightweight library to integrate wizard/steppers in your React app. Some goods about the package:

✨Full TS support
🤘Provider and React Hooks support
💻 Programatic API Dinamic steps updates & DX++
⚛️ Zero-dependencies package
📦 Small bundle: 1kB

More details in https://twitter.com/willmendesneto/status/1454972829884104708
