### ISSUE TITLE
How to handle rest urls (Step path)

### ISSUE THREAD

**Issue by dlplenin** [americanexpress/react-albus#13]
Hi,
Is it possible to use rest url as value of path?
```javascript
<Step path="merlin/idValue">
 <Merlin />
</Step>`
```

or I have to change code like this? (components/Wizard.jsx)

```javascript
    componentWillMount() {
      this.unlisten = this.history.listen(({ pathname }) => {
      // const path = pathname.split('/').pop();
      let path = pathname.split('/').splice(2).join('/');
      const step = this.steps.filter(s => s.path === path)[0];
      if (step) {
        this.setState({
          step,
        });
      }
     });
    }
```
Instead of take last part of pathname I take last parts (skiping 2 firsts).
Pls, suggest me

**Comment by jayjaycross** [comment]
I hadn't considered this use case until now.  I don't think we should `splice(2)` and use everything after the first two parts of the path, but maybe we can make a change like this:
```js
componentWillMount() {
  this.unlisten = this.history.listen(({ pathname }) => {
    const path = pathname.replace(`${this.props.basename}/`, '');
    const step = this.steps.filter(s => s.path === path)[0];
    if (step) {
      this.setState({
        step,
      });
    }
  });
}
```
I think this will work for your use case and be backwards compatible.

**Comment by dlplenin** [comment]
Thanks!, you are right. I figured out that my idea `splice(2)` was not good... your test (spec) did not pass!

I resolved this by checking if phathname contains s.path, but your solution is safer (im going to change).

Now Im facing a problem due to the Component into Step does not resolve the param of restful url __idValue__ in requestState:

```javascript
export class Orco extends RouteHandler {
  constructor(props) {
    super(props);
  }

  static requestState({idValue}) {

  }
.
.
.
}

export default Orco;

```
In a test, I changed createBrowserHistory(forceRefresh: true) instead of createMemoryHistory () ... In *chrome-devtools* I saw the request in the *network* tab, but because I forced the refresh of the screen I was no longer within the flow of react-albus wizard.

Any suggestions would be great!

**Comment by jayjaycross** [comment]
> Component into Step does not resolve the param of restful url idValue in requestState

I'm having trouble following as I'm not sure what `idValue` and `requestState` are.  Do you have a more complete code example?  Or maybe a repo you could point me to?

**Comment by RusinovAnton** [comment]
Hi @crosscompile. I think I have similar question. 
My routing looks like this
`/home/operation/:operationId/<step-name>`
For example, I can have following URLs:

`/home/operation/create/step-1` - for new operation
`/home/operation/32/step-1` - for edit operation

I have trouble understanding how to make it work with Steps

**Comment by khumphrey** [comment]
I have the same question. If I have a fork in my steps - one for create and one for use existing that have different screens that need to be shown... I'm having trouble making it work with Steps.
