### ISSUE TITLE
CLA not working

### ISSUE THREAD

**Issue by AbdealiJK** [americanexpress/react-albus#14]
I opened the link for CLA and it got me to https://cla-assistant.io/americanexpress/

Going here, when I click "Sign in with Github" it gives me a 404 error.

**Comment by jayjaycross** [comment]
Thanks for bringing this up!  It looks like the link needs to include the repository in the path, https://cla-assistant.io/americanexpress/react-albus should work.

@tklever [updated the readme](https://github.com/americanexpress/react-albus/commit/ba56208f9daac9a4340abc2110e9a34ccab4d26e) with the correct link.
