### ISSUE TITLE
`withWizard` example

### ISSUE THREAD

**Issue by loqtor** [americanexpress/react-albus#16]
Hi guys,

I'm currently trying to use the `withWizard` enhancer and I cannot get my head around on what is expecting me to pass in.

Here's what I'm trying:

```:javascript
const ChangeCoverConnected = connect(mapStateToProps, mapDispatchToProps)(ChangeCover);

export default withWizard(ChangeCoverConnected);
```

I get this error:

`Uncaught TypeError: Cannot read property 'init' of undefined`

When trying to debug it, I noticed that when the enhancer is invoked, it (**apparently**) expects a _reference_ to the wizard and that's the part where I'm lost. :)

Can you guys provide an example of how the enhancer should be used?
Thanks.

Cheers!

**Comment by nathanforce** [comment]
Hello! Thanks for reaching out.  

https://codesandbox.io/s/oqmqxnoj2y

I've augmented the redux example app on CodeSandbox with some react-albus stuff in there.  All seems to work fine using `withWizard`.  

What version of react-albus are you using?

**Comment by loqtor** [comment]
Heya,

I'm using 2.0.0.

**Comment by nathanforce** [comment]
@loqtor Be sure you are rendering your `withWizard` wrapped component _within_ a `Wizard`, else it won't be able to access `context.wizard`
