### ISSUE TITLE
Custom step-component not rendering

### ISSUE THREAD

**Issue by yyynnn** [americanexpress/react-albus#26]
Hello!

Why does a custom step component not rendering? Doing it like this results in empty `<Steps>`:
```
const EOFormStep2 = ({stepId}) => (
  <Step id={stepId}>
    <h1>Gandalf</h1>
  </Step>
)

...

 <Steps>
   <EOFormStep2 stepId="EOFormStep2" />
```

**Comment by yyynnn** [comment]
Figured it out:

```
<Steps>
   <Step id="EOFormStep1" render={() => <EOFormStep1 />} />
```

Was confused by this example code ([http://americanexpress.io/react-albus/](http://americanexpress.io/react-albus/)):

```
<Steps>
   <Step id="gandalf">
            <h1 className="text-align-center">Gandalf</h1>
          </Step>
```

**Comment by crosscompile** [comment]
Sorry for the late reply here, but I think the issue with the original example is that `<EOFormStep2>` needs to have the prop `id` instead of `stepId` since that is what `<Steps>` is looking for.

Glad you were able to get it working with a render prop though!
