### ISSUE TITLE
Security error on demo page.

### ISSUE THREAD

**Issue by Northshoot** [americanexpress/react-albus#30]
Hey,

Demo page is down and does gives Security Error as seen in the picture. Tested in Firefox 62.0

<img width="1667" alt="2018-09-13_17-20-14" src="https://user-images.githubusercontent.com/7857361/45522694-7532f600-b779-11e8-9d8b-c7935d488c59.png">

**Comment by crosscompile** [comment]
Yikes!  That looks like an error in the Codesandbox iframe. I haven't been able to replicate but maybe it was a temporary issue with Codesandbox.  Possibly related to:

https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue/12042843#12042843

**Comment by asutedja** [comment]
Similar to @crosscompile, I also have not been able to reproduce the issue, even on Firefox 62.  Most likely related to Codesandbox, though that was a year ago.  Going to close this for now, but if you have more steps to reproduce, we can reopen this issue.
