### ISSUE TITLE
Albus fails to reinitialize

### ISSUE THREAD

**Issue by yyynnn** [americanexpress/react-albus#32]
Hello, running into problem here.

Having steps generate from json (getting from API) from redux store.
Initial value is an empty array. Albus renders this empty 'steps'. Then after getting all of the real data wizard is not re-initializing, resulting in empty render. 

For now i can check beforehand if data is empty, like this: 
```javascript
{!isEmpty(data) && (
              <Wizard>
                   ....
              </Wizard>
            )}
```
but would be nice to handle the re-render inside Albus without unnecessary noise.

**Comment by rizwanad** [comment]
Hi. great library this is.
Can you please cater the solution in this version ?
