### ISSUE TITLE
How to put Step into different file? 

### ISSUE THREAD

**Issue by nicolasxu-bg** [americanexpress/react-albus#37]
It looks like

`
  <Wizard>
    <Steps>
      <Step id="my-step1">
`

wokrs, but if I put `my-step1` into different component, then it does not work. How can I put each step into different files?

**Comment by crosscompile** [comment]
Hi @nicolasxu-bg, [here is a codesandbox](https://codesandbox.io/s/52r3kxzrmk) with steps in different files.

Let me know if anything doesn't make sense!

**Comment by asutedja** [comment]
@nicolasxu-bg Looks like @crosscompile has answered your question, so will be closing this issue.
