### ISSUE TITLE
Calling next method in onNext handler causes infinite loop

### ISSUE THREAD

**Issue by benhodgson87** [americanexpress/react-albus#42]
```js
<Wizard onNext={({ step, next }) => {
  if (step.id) {
    console.log('onNext called')
    next()
  }
}}>
```

Got Albus working fine when running _without_ an `onNext` handler, but now need to add an event that will be called whenever the user successfully navigates to the next step, whilst still navigating them to the next step.

Unfortunately the above example code results in an infinite loop. `onNext` is recursively called until the browser kills the process, presumably as calling `next` results in `onNext` being called, which in turn calls `next` again.

I've managed to get around this by working out the next step and calling `push` instead, however this feels less than ideal.

```js
<Wizard
  onNext={({ step, steps, push }) => {
    if (step.id) {
      console.log('onNext called')
      push(
        steps[steps.findIndex(el => el.id === step.id) + 1].id
      )
    }
  }}
>
```

Is this a bug, or expected behaviour? Is there a better way to call a function upon successful step navigation, without having to call `next` to maintain the default navigation behaviour, which results in this issue?

**Comment by asutedja** [comment]
Sorry for the very late reply.

> Got Albus working fine when running without an onNext handler, but now need to add an event that will be called whenever the user successfully navigates to the next step, whilst still navigating them to the next step.

If `next` is being called, that means the user should be moving to the `next` step anyway.  Are you trying to navigate the user to a step other than the next `step`?  If so, then `push` would make more sense to use.

**Comment by benhodgson87** [comment]
The issue is that when you call the `onNext` handler, it stops taking the user to the next step - as the existing functionality is overriden - and only runs the code provided to `onNext`. This means when you click the next button, your custom code will run, but to actually go to the next step you have to manually call `next` within your custom handler, however this is where the infinite loop is caused, as `next` itself calls `onNext`, which in turn will call `next` again, and so on.
