### ISSUE TITLE
The demo example does not work

### ISSUE THREAD

**Issue by dsomel21** [americanexpress/react-albus#59]
I was trying to see the demo of react albus over at: http://americanexpress.io/react-albus/

But it did not do anything. Also, you probably already know... but the web page does not have an SSL certificate :(

**Comment by jsmartfo** [comment]
Hello @dsomel21 it works for me in Chrome. What browser are you using? 

The SSL part we can totally do: https://americanexpress.io/react-albus/

This was because americanexpress.io was http only when it first launched.

**Comment by wormyy** [comment]
I use firefox and it doesn't work for me either. It works on Chrome.

**Comment by dsomel21** [comment]
I apoligize for the lateness, but yes. It was Firefox. Works on Chromium based Brave browser.

**Comment by dsomel21** [comment]
It is working nicely now!
