### ISSUE TITLE
Render a step repeatedly based on a parameter 

### ISSUE THREAD

**Issue by uraees** [americanexpress/react-albus#64]
I apologize foks if I used this issue ticket instead of a forum post. I did not see a forum link anywhere.

I was wondering how can I do a step repeatedly based on a parameter value ? 

Thanks and appreciate,

uraees

**Comment by jgolden17** [comment]
`Wizard` takes an `onNext` prop that will gets called before every render.  You should be able to control repeated steps from within that callback.  Take a look at the [skip-a-step example](https://github.com/americanexpress/react-albus/blob/master/examples/skip-a-step/index.js#L10).

**Comment by ryhinchey** [comment]
I think this is related to https://github.com/americanexpress/react-albus/issues/69 and https://github.com/americanexpress/react-albus/issues/86.  As always, feel free to re-open.
