### ISSUE TITLE
Anybody getting this Legacy Context API warning in Wizard ? 

### ISSUE THREAD

**Issue by uraees** [americanexpress/react-albus#65]
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Steps, Wizard

Learn more about this warning here: https://fb.me/react-legacy-context
    in Wizard (at XXXXXXX.jsx:70)
    in form (created by Form)
.....
    in App (at src/index.js:34)
    in StrictMode (at src/index.js:10)

**Comment by jgolden17** [comment]
This project is still using the `Component.contextTypes` API.  We should give this some love and look at using hooks in the next major release.

**Comment by jgolden17** [comment]
Closing in favor of #38
