### ISSUE TITLE
Consider a different structure for the examples page

### ISSUE THREAD

**Issue by devnoot** [americanexpress/react-albus#73]
It's nice to have all the code sandboxes there, but when they are all on the same page, it's super laggy.

**Comment by stephjs** [comment]
Hi @nellyk I have an open [PR](https://github.com/americanexpress/react-albus/pull/84) that is a workaround for this issue.

**Comment by nellyk** [comment]
Thank you for your contribution @stephjs

**Comment by nellyk** [comment]
@devnoot  does this resolve the issue you've raised?
